apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: l5ql76iel-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/l5ql76iel-dotnet-basic-gitops